import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import styled from 'styled-components'
import { useState } from 'react'

// import Header from 'components/Header'
import DraggableModal from 'components/draggable/DraggableModal'
import NotiIcon from 'public/images/notification.svg'
import MyPageIcon from 'public/images/mypage.svg'

const Home: NextPage = () => {
  const [modal, setModal] = useState(false)

  return (
    <div className="flex flex-col h-screen bg-gray-100 text-blue">
      <Head>
        <title>Home | GURURU</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className=" flex justify-between items-center w-full top-0 sticky px-4 py-2.5 text-lg font-semibold text-white bg-primary ">
        <div onClick={() => setModal(!modal)}>내위치</div>
        <div className="flex gap-2 items-center">
          <NotiIcon alt="알림페이지로 가기" width="30" heigth="30" />
          <MyPageIcon alt="마이페이지로 가기" width="17" heigth="17" />
        </div>
      </header>
      <div className="flex items-center justify-center px-4 pb-4 rounded-b-xl bg-primary">
        <input type="text" className="w-full h-10 border-none px-3" />
      </div>
      <Nav.Container>
        <Link href="">
          <a className="item">내주변</a>
        </Link>
        <Link href="">
          <a className="item">LIVE</a>
        </Link>
        <Link href="">
          <a className="item">예약관리</a>
        </Link>
        <Link href="">
          <a className="item">마이펫</a>
        </Link>
        <Link href="/mypage">
          <a className="item">마이페이지</a>
        </Link>
      </Nav.Container>
      {modal && <DraggableModal />}
    </div>
  )
}

const Nav = {
  Container: styled.nav`
    display: grid;
    height: 70%;
    margin-top: 1rem;
    padding: 0 1rem;
    grid-template-rows: 1fr 0.5fr 1fr;
    grid-template-columns: repeat(2, 1fr);
    gap: 1rem;
    font-family: 'Black Han Sans', sans-serif;
    font-size: ${({ theme }) => theme.size.base};

    .item {
      width: 100%;
      padding: 1rem;
      background-color: ${({ theme }) => theme.colors.white};
      border-radius: 1.2rem;
      box-shadow: 1px 2px 5px 0px rgba(0, 0, 0, 0.2);
    }
    .item:nth-child(3) {
      grid-column: 1/3;
    }
  `,
}

export default Home
