import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Script from 'next/script'
import React from 'react'

import styles from 'styles/pages/Home.module.scss'

const Home: NextPage = () => {
  const kakaoInit = () => {
    const kakao = (window as any).Kakao
    if (!kakao.isInitialized()) {
      kakao.init('5afb2c4d6443d45e582daed7cd01634a')
    }
    kakao.Auth.authorize({ redirectUri: 'http://localhost:3000/auth/kakao' })
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Home | GURURU</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script
        src="https://t1.kakaocdn.net/kakao_js_sdk/2.0.0/kakao.min.js"
        integrity="sha384-PFHeU/4gvSH8kpvhrigAPfZGBDPs372JceJq3jAXce11bVA6rMvGWzvP4fMQuBGL"
        crossOrigin="anonymous"
      />
      <div style={{ display: 'flex', justifyContent: 'center' }}>
        <Image
          src="/images/logo.png"
          width={256}
          height={100}
          alt="내 애완동물 미용은 구루루"
          priority
        />
      </div>
      <button className={styles.button} onClick={kakaoInit}>
        <a className={styles.anchor}>
          <Image src="/images/kakaoLogo.png" alt={''} width={30} height={30} />
          <span className={styles.span}>카카오 로그인</span>
        </a>
      </button>
    </div>
  )
}

export default Home
